# Generated by Django 5.0.3 on 2024-03-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(default='All', max_length=100),
            preserve_default=False,
        ),
    ]
